#!/bin/sh
# Script to 
#  1 - init DCHP and get next-server address
#  2 - Mount NFS share

# Running pump if necessary
pump -s 2> /dev/null || pump
export imaging_server=$(pump -s | awk '/Next server/ { print $3 }')
export SHORTMAC=$(cat /sys/class/net/eth0/address | tr '[:lower:]' '[:upper:]'|sed 's/://g')
export MAC=$(cat /sys/class/net/eth0/address | tr '[:lower:]' '[:upper:]')
export HOSTNAME="Unkown-host"
export HOSTNAME=$(echo -en "\032\00Mc:$MAC" | nc -p 1001 -w 2 10.252.4.69 1001)
export IPSERVER=$imaging_server

if [ ! $? -eq 0 ] || [ -z $imaging_server ]; then
    echo "Failed to get imaging_server IP, fatal error"
    exit 0
fi

# Mounting imaging server NFS
if [ ! -d /imaging_server/masters/ ]; then
    mkdir -p /imaging_server/masters/
fi
mount $imaging_server:/var/lib/pulse2/imaging/masters/ /imaging_server/masters/
# Mounting postinst share
if [ ! -d /opt/ ]; then
    mkdir -p /opt/
fi
mount $imaging_server:/var/lib/pulse2/imaging/postinst/ /opt/

source /etc/init.d/postinst_macros.sh

# Revotools compativility stuff
echo "eth0" > /etc/eth
cat /sys/class/net/eth0/address | tr '[:lower:]' '[:upper:]' > /etc/mac
echo "Next_server=$imaging_server" > /etc/netinfo.sh
