#!/bin/bash
# Any error breaks the script
set -e
# Trap Ctrl-C Ctrl-Z
trap "" 2 20

# Mounting NFS shares
source /etc/init.d/mount_pulse_nfs

# Removing home/partimag
rm -r /home/partimag
# Create a symlink to imaging_server/masters
ln -s /imaging_server/masters /home/partimag

# =======================================================
# Copying the Fake partclone
# =======================================================

pclone_bins=$(echo /usr/sbin/partclone.{btrfs,dd,exfat,extfs,fat,hfsp,imager,jfs,minix,ntfs,reiser4,reiserfs,ufs,vmfs,vmfs5,xfs})

# Copy the fake partclone to /usr/sbin
echo $pclone_bins| xargs -n1 cp /usr/share/davos/relay_client/partclone.fake

# =======================================================
# Start image creation
# =======================================================

# Reset the partclone_index
echo "0" > /tmp/partclone_index

# Launch savimg to generate all image files 
yes | /usr/sbin/ocs-sr -nogui -q2 -c -j2 -z1 -i 20000000 -sc -p true savedisk image sda
