#!/bin/bash
#
# (c) 2015-2016 Siveo, http://www.siveo.net
#
# $Id$
#
# This file is part of Pulse 2, http://www.siveo.net/solutions/pulse/
#
# Pulse 2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Pulse 2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pulse 2.  If not, see <http://www.gnu.org/licenses/>.
#

bootservice_dir="/opt/scripts"

# If BOOTSERVICE_SCRIPT doesn't exist, leaving
[ ! -f $bootservice_dir/$BOOTSERVICE_SCRIPT ] && exit 0

# Run the bootservice
bash $bootservice_dir/$BOOTSERVICE_SCRIPT
sleep 2
exit 0

