#!/bin/bash
# Any error breaks the script
set -e
# Trap Ctrl-C Ctrl-Z
trap "" 2 20

# Mounting NFS shares
source /etc/init.d/mount_pulse_nfs

# Get multicast group
multicast_group=$(grep 'davos_multicast_group=' /proc/cmdline | sed 's|.*davos_multicast_group=\([^ ]*\).*|\1|')
[ -z "$multicast_group" ] && multicast_group='0'

# Copy clonezilla stuff to /home/partimag
cp -r /imaging_server/masters/tmp.$multicast_group /home/partimag/image || (dialog --title "Erreur" --msgbox "Aucune session de restauration multicast trouvée pour le groupe $multicast_group . Démarrez le serveur relai multicast d'abord." 10 50 && reboot )

# =======================================================
# Copying the Fake partclone
# =======================================================

pclone_bins=$(echo /usr/sbin/partclone.{btrfs,dd,exfat,extfs,fat,hfsp,imager,jfs,minix,ntfs,reiser4,reiserfs,ufs,vmfs,vmfs5,xfs})

# Copy the fake partclone to /usr/sbin
echo $pclone_bins| xargs -n1 cp /usr/share/davos/relay_client/partclone.fake

# =======================================================
# Start restore
# =======================================================

# Reset the partclone_index
echo "0" > /tmp/partclone_index

# Launch savimg to generate all image files 
yes | /usr/sbin/ocs-sr -icds -nogui -g auto -e1 auto -e2 -c -r -j2 -p true restoredisk image sda

# Trying to read master_id file
MountSystem
master_id=$(cat /mnt/master_id)
#rm -f /mnt/master_id
umount /mnt
if [ ! -z $master_id ]; then
  echo "Running postinstall scripts ..."
  for z in /imaging_server/masters/$master_id/postinst.d/*; do
    source $z || true
  done
fi
